domain: both.rocks
url: https://both.rocks/
title: Both rocks!
name: Both
description: Both es una escuela y un laboratorio. Un punto de encuentro entre tecnología y humanismo.

exclude: [both_web.code-workspace, README.md, subir_both.sh]

collections:
  fichas:
    # output: true
    # permalink: /ficha/:name
  proyectos:
    output: true
    permalink: /proyecto/:name