domain: both.rocks
url: https://both.rocks
title: Both rocks!
name: Both

exclude: [both_web.code-workspace, README.md, subir_both.sh, subir_both_dev.sh]

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

collections:
  fichas:
    # output: true
    # permalink: /ficha/:name
  proyectos:
    output: true
    permalink: /proyecto/:name
    sort_by: order
  eventos:
    output: true
    permalink: /evento/:name
